name: scene_alert
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http:

  google_maps_flutter: ^0.5.21+14
  flutter_secure_storage: ^3.3.1+1
  geolocator: ^5.1.5
  provider: ^3.1.0+1

  # The following adds local notifications support
  flutter_local_notifications: ^0.8.4+2
  # The following is for flutter notifications support
  path_provider: ^1.4.2


  # iOS icons
  #cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - images/404_image.png
    - images/blue_foreground.png
    - images/fireMarker128.png
    - images/hazardMarker128.png
    - images/hazardMedicalMarker128.png
    - images/medicalMarker128.png
    - images/multiMarker128.png
    - images/policeHazardMarker128.png
    - images/policeHazardMedicalMarker128.png
    - images/policeMarker128.png
    - images/policeMedicalMarker128.png
    - assets/dark.json

  fonts:
    - family:  SceneAlert
      fonts:
       - asset: fonts/SceneAlert.ttf