/// Flutter icons SceneAlert
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  SceneAlert
///      fonts:
///       - asset: fonts/SceneAlert.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class SceneAlert {
  SceneAlert._();

  static const _kFontFam = 'SceneAlert';

  static const IconData firemarker = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData hazardmarker = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData medicalmarker = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData policemarker = const IconData(0xe803, fontFamily: _kFontFam);
}
